### ISSUE TITLE
Genesis block mismatch - f2ba87b7a6b3c3ff (!= c426841a7dc2c176)

### ISSUE THREAD

**Issue by Messi-Q** [vntchain/go-vnt#111]
**Please using command `gvnt bug` report a bug.** It will auto fill below fileds.

gvnt --networkid 2 --datadir . --port 3001 --vntbootnode "/ip4/101.37.164.86/tcp/3001/ipfs/1kHVWqjwrMKm7fjY3WhrHNUvWYX2XXNyHomP4HDFE5u6S2B" --syncmode full --rpc --rpcaddr 0.0.0.0 --rpcport 8880 --rpcapi="db,core,net,vnt,personal" console

GetPeerByRemoteID peerid="<peer.ID 1kHHMELQGozJeaGckomHSMSymwgYWj2cRR2uSgn9y5eB7rV>" peer got="&{rw:0xc019b35400 log:0xc019b35440 events:<nil> err:0xc0045d4960 closed:false messenger:map[vnt:0xc019c4f980 shh:0xc019c4f9e0] wg:{noCopy:{} state1:[0 2 0]}}"
INFO [07-17|11:13:11] test vnt protocol handshake              encounter error=0xc005e34540
INFO [07-17|11:13:11] p2p-test                                 run protocol error log="Genesis block mismatch - f2ba87b7a6b3c3ff (!= c426841a7dc2c176)"
INFO [07-17|11:13:11] p2p-test wait complete!                  peerid="<peer.ID 1kHHMELQGozJeaGckomHSMSymwgYWj2cRR2uSgn9y5eB7rV>"
INFO [07-17|11:13:11] Removing p2p peer                        peers="<peer.ID 1kHHMELQGozJeaGckomHSMSymwgYWj2cRR2uSgn9y5eB7rV>"
INFO [07-17|11:13:11] p2p-test, stream data comming 
INFO [07-17|11:13:11] p2p-test                                 peers="map[<peer.ID 1kHLtKvu9KuHszCE4HJHPAff3W3muZEQz6xE5GZAmrbjZtE>:0xc000e09ef0 <peer.ID 1kHfUmt3atwYaavGk18t4Ni3S4hnKuQYvqpagiiToRAZKAr>:0xc0098f5810 <peer.ID 1kHHupcnkJeRD5zsK82xJnjTypkspG5fF2AagPFyddLF8jN>:0xc000e6e550 <peer.ID 1kHSZLkEvs1t5zFt9FCUciwhE8qjzo5DEAXz1Bcut5wpDsU>:0xc003908f50 <peer.ID 1kHPq9gUWVvFaBQCKUuUJprJeJjEZkPtr71tGvXB6AR8kEK>:0xc01bb6c4b0 <peer.ID 1kHVWqjwrMKm7fjY3WhrHNUvWYX2XXNyHomP4HDFE5u6S2B>:0xc01b54da40 <peer.ID 1kHGkNTW77bHQKCwGKne9yFETrcf5ctnjdgKVijUwSbNS2F>:0xc001e24af0 <peer.ID 1kHPSqs89VDi5Ngysw4Lsmwc9FFnfaynS7R5rGyrZpaoDjz>:0xc01bfb5590 <peer.ID 1kHGDL2PJdLudK6qznTwhrxMAa8ZSrwT517LPix6kWDAAGT>:0xc0189abcc0 <peer.ID 1kHQCsdu9BxYXw8biEqUgpXZie5rGm7sbxDTxDUocMoNB5F>:0xc00b4b6fa0 <peer.ID 1kHTk36NyVdcPBAV3Z3PnBXeGpsun6dX1LGY4GTddYdK7Jx>:0xc0061cc3c0 <peer.ID 1kHHMELQGozJeaGckomHSMSymwgYWj2cRR2uSgn9y5eB7rV>:0xc000d91c70 <peer.ID 1kHfn7yfdJx4x2f8fh7ZzxFuA5f5KBGyfUWgBUHXMQWKFaL>:0xc01badeaf0 <peer.ID 1kHU5pme4yUcYJBhaeC3FtPLcf5KehRwJtqPdiBr8z45YYH>:0xc00aaa9f90 <peer.ID 1kHJiPvxGsHZJyoSGhB32zVjcVUDZRWfMgR3nRr5B6oVC5a>:0xc0038f93b0 <peer.ID 1kHbb8Hx9uSbpzfrKVhMCYmksJcZU6gZp63Ycgn3QRpSafF>:0xc000ffab40]"
INFO [07-17|11:13:11] yhx-test                                 send message type=0
INFO [07-17|11:13:11] test vnt protocol handshake              going to send handshake msg to="<peer.ID 1kHHMELQGozJeaGckomHSMSymwgYWj2cRR2uSgn9y5eB7rV>" msg with ProtocolVersion=62
INFO [07-17|11:13:11] yhx-test                                 send message type=0
INFO [07-17|11:13:11] p2p-test                                 GetPeerByRemoteID peerid="<peer.ID 1kHHMELQGozJeaGckomHSMSymwgYWj2cRR2uSgn9y5eB7rV>" peer got="&{rw:0xc019b23b60 log:0xc019b23ba0 events:<nil> err:0xc009411620 closed:false messenger:map[vnt:0xc00178c840 shh:0xc00178c8a0] wg:{noCopy:{} state1:[0 2 0]}}"
INFO [07-17|11:13:11] p2p-test, stream data comming 
INFO [07-17|11:13:11] p2p-test                                 incoming message="{Header:[231 0 0 0 0] Body:{ProtocolID:shh Type:0 ReceivedAt:2019-07-17 11:13:11.517233 +0800 CST m=+35.083488605 PayloadSize:12 Payload:0xc01b1b7110}}"

I followed this tutorial.
https://hubscan.vnt.link/developer/test

#### System information

Version: 0.6.0-beta
Go Version: go1.11.2
OS: darwin
uname -v: Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54

**Comment by ruopuzi** [comment]
this bug is fixed
