### ISSUE TITLE
友情提示：代码中包含很多以太坊源码注释

### ISSUE THREAD

**Issue by libangzhu** [vntchain/go-vnt#20]
。。。

**Comment by Shitaibin** [comment]
@libangzhu 谢谢提醒。Hubble Network项目是借鉴以太坊架构开发的，我们实现了新的共识、虚拟机、P2P，我们感谢并认可以太坊团队的成果，要保留以太坊的版权，所以很多源文件都可以看到以太坊源码的版权声明和注释。

**Comment by ruopuzi** [comment]
由于这个不是一个bug，将关闭这个issue
