### ISSUE TITLE
源码编译成可执行文件后，按照官网搭建的测试网络不挖矿

### ISSUE THREAD

**Issue by shanpengfei7** [vntchain/go-vnt#64]
源码编译成可执行文件后，按照`搭建本地Hubble网络`搭建的测试网络不挖矿，区块高度一直是0，开始挖矿会报出一个警告`There is no witness candidates. If you want to be a witness, please register now. `。

**Comment by Shitaibin** [comment]
@shanpengfei7 做以下检查

1. 解锁见证人节点的账号
2. 开启共识

参考：
https://github.com/vntchain/vnt-documentation/blob/master/introduction/set-up-vnt-network/set-up-4-node-vnt-network.md#%E6%89%93%E5%8C%85%E5%8C%BA%E5%9D%97
