### ISSUE TITLE
合约调用和事件未实现？？

### ISSUE THREAD

**Issue by Timmy-crypto** [vntchain/go-vnt#72]
合约func_table.go中　关于合约调用OpNameContractCall和事件OpNameEvent这两个没有实现。
vnt现在不支持合约调用和合约事件通知?

另外，vnt　bottle编译器和　wasm虚拟机如何处理对　c 标准库的函数调用，例如在合约编写时
调用文件操作函数。在编译器和wasm虚拟机的相应代码中未看到对标准库的额外功能处理的部分

**Comment by ruopuzi** [comment]
你好！
### 第一个问题

> OpNameContractCall和OpNameEvent两个指令的参数是可变的，所以没有直接定义在func_table.go中，而是动态的生成，代码请参考：
> https://github.com/vntchain/go-vnt/blob/master/core/wavm/env_funcs.go#L71-L159


### 第二个问题

> bottle和wasm虚拟机目前并不支持C标准库，因为编译出来的代码量过大。
> 关于文件操作，由于合约的数据都存储于区块链上，合约只能操作statedb中的数据，所以在语境上并不支持做文件IO操作。

**Comment by Timmy-crypto** [comment]
多谢回复。对与c标准库还有些疑问，bottle和wasm虚拟机现在不支持c标准库，那么bottle编译合约代码时，若合约使用了标准库功能，编译器如何检查的，没看到具体代码。　另外虚拟机对这种不合法的wasm代码又如何限制的?

**Comment by MaggieNgWu** [comment]
在智能合约中加入文件操作后, 观察到的现象是:
1. 使用Bottle编译, 并不报错
2. 部署合约能成功
3. 调用功能时, 文件操作并没生效

由从这个现象推出, 编译和部署时不会对代码进行检查和过滤. 这样是否会有安全隐患呢?
而最后一步, 功能调用时, 文件操作未生效, 这又是什么原因呢?

**Comment by ooozws** [comment]
> 多谢回复。对与c标准库还有些疑问，bottle和wasm虚拟机现在不支持c标准库，那么bottle编译合约代码时，若合约使用了标准库功能，编译器如何检查的，没看到具体代码。　另外虚拟机对这种不合法的wasm代码又如何限制的?

标准库大部分方法会编译出syscall等系统调用的方法，这些方法不在实现的func_table列表中，虚拟机会在这里https://github.com/vntchain/go-vnt/blob/master/vendor/github.com/vntchain/vnt-wasm/wasm/imports.go#L157
验证是否有方法是未在func_table中实现的，如果没实现，虚拟机会返回错误

**Comment by ooozws** [comment]
> 在智能合约中加入文件操作后, 观察到的现象是:
> 
> 1. 使用Bottle编译, 并不报错
> 2. 部署合约能成功
> 3. 调用功能时, 文件操作并没生效
> 
> 由从这个现象推出, 编译和部署时不会对代码进行检查和过滤. 这样是否会有安全隐患呢?
> 而最后一步, 功能调用时, 文件操作未生效, 这又是什么原因呢?

文件操作等c的标准库方法应该会导致部署合约失败，因为这些方法会编译出syscall等系统调用方法，这些系统调用的方法不在func_table支持的方法中

**Comment by MaggieNgWu** [comment]
建议在Bottle中加入func_table检查, 防止用户部署不合格代码, 浪费Gas

**Comment by ooozws** [comment]
> 建议在Bottle中加入func_table检查, 防止用户部署不合格代码, 浪费Gas

是的，很好的建议，bottle是可以做这层校验的

**Comment by MaggieNgWu** [comment]
请问合约数据和代码都存在状态树的Code中吗? @ooozws @ruopuzi 
``code := wavm.StateDB.GetCode(addr)``

> ### 第一个问题
> > OpNameContractCall和OpNameEvent两个指令的参数是可变的，所以没有直接定义在func_table.go中，而是动态的生成，代码请参考：
> > https://github.com/vntchain/go-vnt/blob/master/core/wavm/env_funcs.go#L71-L159

**Comment by ooozws** [comment]
> 请问合约数据和代码都存在状态树的Code中吗? @ooozws @ruopuzi
> `code := wavm.StateDB.GetCode(addr)`
> 
> > ### 第一个问题
> > > OpNameContractCall和OpNameEvent两个指令的参数是可变的，所以没有直接定义在func_table.go中，而是动态的生成，代码请参考：
> > > https://github.com/vntchain/go-vnt/blob/master/core/wavm/env_funcs.go#L71-L159

合约内部的状态变量（用关键字KEY声明的变量）存在状态树中
```
func (self *StateDB) SetState(addr common.Address, key, value common.Hash) 

func (self *StateDB) GetState(addr common.Address, bhash common.Hash) common.Hash 
```

合约的代码是存在code中的

**Comment by MaggieNgWu** [comment]
谢谢大神 @ooozws
